name: deploy.yml
on:
  workflow_call:
    inputs:
      artifact-name:
        description: Name of the artifact to deploy
        required: true
        type: string

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v5
        with:
          name: ${{inputs.artifact-name}}

      - name: Setup Pages
        uses: actions/configure-pages@v4
        with:
          enablement: true

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

      - name: Deploy to GH pages
        id: deployment
        uses: actions/deploy-pages@v4