name: main-push.yml
on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      git-ref: 'main'
  deploy:
    uses: ./.github/workflows/deploy.yml
    needs: build
    with:
      artifact-name: 'artifact-main'