name: main-push.yml
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    uses: ./.github/workflows/build.yml
  deploy:
    uses: ./.github/workflows/deploy.yml
    needs: build